ui = navbarPage(title = span(div(img(src = "spotifySlugLogo.jpg", 
                                     height = 30,
                                     width = 30), 
                                 strong("Spotify Slug")), style = "color: #1DB954"),
                windowTitle = "Spotify Slug",
                inverse = T,
                useShinyjs(),
                includeCSS("www/styles.css"),
                # Panel 1 - Introduction and Authentication)
                tabPanel(title = span(strong("Welcome!"), style = "color: #1DB954"),
                         fluidPage(
                           sidebarLayout(
                             sidebarPanel(h4(strong("First steps: Authentication")), 
                                          p("To look at your personal Spotify data, you will need to log in to ", a(href = "https://developer.spotify.com/", "Spotify for Developers,"), 'go to "Dashboard," and click "Create an App." This will prompt you to give your app a name and a description. Once your app is set up, you will be able to access a "Client ID" and "Client Secret" code - this is what Spotify Slug needs for your authentication.'), 
                                          hr(),
                                          textInput("authID", 
                                                    label = "Enter your Client ID"), 
                                          textInput("secret", 
                                                    label = "Enter your Client Secret"), 
                                          actionButton("authButton", 
                                                       label = "Authenticate!"), 
                                          br(), 
                                          br(),
                                          strong(tags$span(style = "color: #579559"), 
                                                 # textOutput("loadingMessage"),
                                                 textOutput("validate_message")),
                                          br()),
                             mainPanel(h3(strong("Welcome to Spotify Slug!")), 
                                       p("This is a web application that analyses patterns in a user's Spotify listening data by accessing the publicly-available ", a(href = "https://developer.spotify.com/documentation/web-api/", "Spotify API."), " Authenticate your account and start exploring!"),
                                       p("Created by Spotify user ", a(href = "https://open.spotify.com/user/bananaslug-10?si=a04c3557683c45bf", "bananaslug-10.")),
                                       div(img(src = "spotifySlugLogo.jpg", 
                                               height = 500, 
                                               width = 500), 
                                           style = "text-align: center;"))
                           )
                         )), 
                
                # Panel 2 - Top Artists and associated stats
                tabPanel(title = span(strong("Your Top Artists"), style = "color: #1DB954"), 
                         fluidPage(
                           sidebarLayout(
                             sidebarPanel(h3(strong("Who are your favorite artists?")), 
                                          p("Select a time frame over which to view your top 50 artists. Please note that the time frames are ", em("approximate"), " and that data may take time to update."), 
                                          hr(), 
                                          selectInput("artistsTime", 
                                                      label = "Select a time frame", 
                                                      choices = c("last 4 weeks" = "short_term", 
                                                                  "last 3 months" = "medium_term", 
                                                                  "all time" = "long_term"), 
                                                      selected = "short_term"),
                                          actionButton("generateArts", 
                                                       label = "Load"),
                                          hr(), 
                                          h4(strong("Your Top Genres")), 
                                          helpText("Hover over any genre in the wordcloud for details!"),
                                          withLoader(wordcloud2Output("genresCloud"), 
                                                     type = "html", 
                                                     loader = "pacman")),
                             mainPanel(tabsetPanel(type = "tabs", 
                                                   tabPanel(h2(strong("Your Top Artists")), 
                                                            htmlOutput("defaultTextArts"),
                                                            br(),
                                                            withLoader(dataTableOutput("artistsTable"),
                                                                       loader = "pacman")),
                                                   tabPanel(h2(strong("Artists for You")), 
                                                            br(), 
                                                            # htmlOutput("defaultTextArts"),
                                                            uiOutput("topArtistsUI"), 
                                                            actionButton("recArtsButton", 
                                                                         label = "Load"),
                                                            hr(),
                                                            htmlOutput("selectedTopArt"),
                                                            withLoader(dataTableOutput("recArtsTable"), 
                                                                       loader = "pacman")),
                                       br()))
                           )
                         )), 
                # Panel 3 - Top Tracks
                tabPanel(title = span(strong("Your Top Tracks"), style = "color: #1DB954"), 
                         fluidPage(
                           sidebarLayout(
                             sidebarPanel(h3(strong("What are your favorite tracks?")),
                                          p("Select a time frame upon which to view your top 50 tracks. Again, time frames are ", em("approximate, "), "and your data may not update immediately."),
                                          hr(), 
                                          selectInput("tracksTime", 
                                                      label = "Select a time frame", 
                                                      choices = c("last 4 weeks" = "short_term",
                                                                  "last 3 months" = "medium_term", 
                                                                  "all time" = "long_term"), 
                                                      selected = "short_term"),
                                          actionButton("generateTracks", 
                                                       label = "Load"), 
                                          hr(), 
                                          h4(strong("A look at your most-represented artists")),
                                          helpText("Hover over the donut plot for details!"),
                                          div(withLoader(plotlyOutput("pieTable"), 
                                                         type = "html", 
                                                         loader = "pacman"), align = "center"),
                                          ),
                             mainPanel(tabsetPanel(type = "tabs", 
                                                   tabPanel(h2(strong("Your Top Tracks")), 
                                                            br(), 
                                                            htmlOutput("defaultTextTracks"),
                                                            withLoader(dataTableOutput("tracksTable"), 
                                                                       type = "html", 
                                                                       loader = "pacman")), 
                                                   tabPanel(h2(strong("Your Stats")),
                                                            br(), 
                                                            # htmlOutput("defaultTextTracks"),
                                                            fluidRow(
                                                              column(6, 
                                                                     h4(strong("When were your favorite tracks released?")), 
                                                                     htmlOutput("yearsAnnotate"),
                                                                     br(),
                                                                     withLoader(plotOutput("trackYears"), 
                                                                                type = "html", 
                                                                                loader = "pacman")), 
                                                              column(6, 
                                                                     h4(strong("How mainstream are your favorite tracks?")),
                                                                     htmlOutput("trackAnnotate"), 
                                                                     br(),
                                                                     withLoader(plotOutput("trackPops"), 
                                                                                type = "html", 
                                                                                loader = "pacman"))
                                                            ), 
                                                            br(), 
                                                            fluidRow(
                                                              column(4, 
                                                                     wellPanel(h4(strong("Your oldest and newest top tracks")), 
                                                                               htmlOutput("yearsMinMax"))),
                                                              column(4, 
                                                                     wellPanel(h4(strong("Your least and most popular tracks")), 
                                                                               htmlOutput("popMinMax"))), 
                                                              column(4, 
                                                                     wellPanel(h4(strong("Your favorite album")), 
                                                                               htmlOutput("favoriteAlbum")))
                                                            ),
                                                            # h4(strong("A look at the audio features of your top tracks")),
                                                            # fluidRow(
                                                            #   column(4,
                                                            #          p(strong("Valence")),
                                                            #          plotOutput("valencePlot")), 
                                                            #   column(4, 
                                                            #          p(strong("Energy")), 
                                                            #          plotOutput("energyPlot")), 
                                                            #   column(4, 
                                                            #          p(strong("Danceability")), 
                                                            #          plotOutput("dancePlot"))
                                                            # )
                                                   ),
                                                   tabPanel(h2(strong("Tracks for You")), 
                                                            br(), 
                                                            p('Based on your selected time frame, here are some tracks that the Spotify API thinks you will also like...'),
                                                            # htmlOutput("defaultTextTracks"),
                                                            withLoader(dataTableOutput("trackRecsTable"), 
                                                                       type = "html", 
                                                                       loader = "pacman"))), 
                                       br(),
                                       )
                           )
                         ))
)
