ui = navbarPage(title = span(div(img(src = "spotifySlugLogo.jpg", 
                                     height = 30,
                                     width = 30), 
                                 strong("Spotify Slug")), style = "color: #1DB954"),
                windowTitle = "Spotify Slug",
                inverse = T,
                useShinyjs(),
                includeCSS("www/styles.css"),
                # Panel 1 - Introduction and Authentication)
                tabPanel(title = span(strong("Welcome!"), style = "color: #1DB954"),
                         fluidPage(
                           sidebarLayout(
                             sidebarPanel(h4(strong("First steps: Authentication")), 
                                          p("To look at your personal Spotify data, you will need to log in to ", a(href = "https://developer.spotify.com/", "Spotify for Developers,"), 'go to "Dashboard," and click "Create an App." This will prompt you to give your app a name and a description. Once your app is set up, you will be able to access a "Client ID" and "Client Secret" code - this is what Spotify Slug needs for your authentication.'),
                                          p('You will also have to go to "Edit Settings," and set "Redirect URIs" to the following: http://localhost:1410/'),
                                          p("Now you should be good to go!"),
                                          hr(),
                                          textInput("id", 
                                                    label = "Enter your Client ID"), 
                                          textInput("secret", 
                                                    label = "Enter your Client Secret"), 
                                          actionButton("authButton", 
                                                       label = "Authenticate!"), 
                                          br(), 
                                          br(),
                                          strong(tags$span(style = "color: #579559"), 
                                                 textOutput("validate_message")),
                                          br()),
                             mainPanel(h3(strong("Welcome to Spotify Slug!")), 
                                       p("This is a web application that analyses patterns in a user's Spotify listening data by accessing the publicly-available ", a(href = "https://developer.spotify.com/documentation/web-api/", "Spotify API."), " Authenticate your account and start exploring!"),
                                       p("Created by Spotify user ", a(href = "https://open.spotify.com/user/bananaslug-10?si=a04c3557683c45bf", "bananaslug-10.")),
                                       div(img(src = "spotifySlugLogo.jpg", 
                                               height = 500, 
                                               width = 500), 
                                           style = "text-align: center;"))
                           )
                         )), 
                
                # Panel 2 - Top Artists and associated stats
                tabPanel(title = span(strong("Your Top Artists"), style = "color: #1DB954"), 
                         fluidPage(
                           sidebarLayout(
                             sidebarPanel(h3(strong("Who are your favorite artists?")), 
                                          p("Select a time frame over which to view your top 50 artists. Please note that the time frames are ", em("approximate"), " and that data may take time to update."), 
                                          hr(), 
                                          selectInput("artistsTime", 
                                                      label = "Select a time frame", 
                                                      choices = c("last 4 weeks" = "short_term", 
                                                                  "last 3 months" = "medium_term", 
                                                                  "all time" = "long_term"), 
                                                      selected = "short_term"),
                                          hr(), 
                                          h4(strong("Your Top Genres")), 
                                          helpText("Hover over any genre in the wordcloud for details!"),
                                          wordcloud2Output("genresCloud")),
                             mainPanel(h2(strong("Your Top Artists")), 
                                       br(),
                                       withLoader(dataTableOutput("artistsTable"), 
                                                  type = "html", 
                                                  loader = "pacman"), 
                                       br())
                           )
                         )), 
                # Panel 3 - Top Tracks
                tabPanel(title = span(strong("Your Top Tracks"), style = "color: #1DB954"), 
                         fluidPage(
                           sidebarLayout(
                             sidebarPanel(h3(strong("What are your favorite tracks?")),
                                          p("Select a time frame upon which to view your top 50 tracks. Again, time frames are ", em("approximate, "), "and your data may not update immediately."),
                                          p('Based on your selected time frame, you can explore the "Tracks for You" tab to look at some tracks that the Spotify API thinks you will also like.'),
                                          hr(), 
                                          selectInput("tracksTime", 
                                                      label = "Select a time frame", 
                                                      choices = c("last 4 weeks" = "short_term",
                                                                  "last 3 months" = "medium_term", 
                                                                  "all time" = "long_term"), 
                                                      selected = "short_term"), 
                                          hr(), 
                                          h4(strong("A look at the most-represented artists")), 
                                          plotOutput("pieTable"), 
                                          hr(), 
                                          h4(strong("When were your favorite tracks released?")), 
                                          plotOutput("trackYears"),
                                          hr(),
                                          h4(strong("How mainstream are your favorite tracks?")),
                                          htmlOutput("trackAnnotate"),
                                          br(),
                                          plotOutput("trackPops")),
                             mainPanel(tabsetPanel(type = "tabs", 
                                                   tabPanel(h2(strong("Your Top Tracks")), 
                                                            br(), 
                                                            withLoader(dataTableOutput("tracksTable"), 
                                                                       type = "html", 
                                                                       loader = "pacman")), 
                                                   tabPanel(h2(strong("Tracks for You")), 
                                                            br(), 
                                                            withLoader(dataTableOutput("trackRecsTable"), 
                                                                       type = "html", 
                                                                       loader = "pacman"))), 
                                       br(), 
                                       hr(), 
                                       h4(strong("A look at the audio features of your top tracks")), 
                                       fluidRow(
                                         column(4,
                                                p(strong("Valence")),
                                                plotOutput("valencePlot")), 
                                         column(4, 
                                                p(strong("Energy")), 
                                                plotOutput("energyPlot")), 
                                         column(4, 
                                                p(strong("Danceability")), 
                                                plotOutput("dancePlot"))
                                       ))
                           )
                         ))
)
